backend/controllers/MoviesController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Movies;
use app\models\UploadForm;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MoviesController implements the CRUD actions for Movies model.
 */
class MoviesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Movies models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Movies::find(),
        ]);

        $dataProvider->pagination->pageSize = 5;

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Movies model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Movies model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new Movies();
        $upload = new UploadForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $upload->imageFile = UploadedFile::getInstance($model, 'image');
            if (!is_null($upload->imageFile)) {
//                $upload->imageFile = UploadedFile::getInstance($model, 'image');
                $upload->id = $model->id;
                $upload->upload();

                $model->image = $upload->filepath . $upload->filename;
                $model->save();
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Movies model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = $this->findModel($id);
        $old_model = $this->findModel($id);
        $upload = new UploadForm();

        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($model, 'image');

            if (!is_null($upload->imageFile)) {

                file_exists($old_model->image) ? unlink($old_model->image) : '';

//                $upload->imageFile = UploadedFile::getInstance($model, 'image');
                $upload->id = $model->id;
                $upload->upload();

                $model->image = $upload->filepath . $upload->filename;
                $model->save();
            } else {
                $model->image = $old_model->image;
            }

            $model->save();

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Movies model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Movies model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movies the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Movies::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionUpload()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->upload()) {
                // file is uploaded successfully
                return;
            }
        }

        return $this->render('upload', ['model' => $model]);
    }
}

frontend/controllers/MoviesController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Movies;
use app\models\MoviesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;

/**
 * MoviesController implements the CRUD actions for Movies model.
 */
class MoviesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Movies models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MoviesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 2;

        $query = Movies::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 2]);
        $models = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'models' => $models,
            'pages' => $pages,
        ]);
    }

    /**
     * Displays a single Movies model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Movies model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Movies();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Movies model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Movies model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Movies model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movies the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Movies::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/movies/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MoviesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="movies-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'title') ?>

<!--    --><?//= $form->field($model, 'title') ?>
<!---->
<!--    --><?//= $form->field($model, 'duration') ?>
<!---->
<!--    --><?//= $form->field($model, 'year') ?>
<!---->
<!--    --><?//= $form->field($model, 'genre') ?>

    <?php // echo $form->field($model, 'director') ?>

    <?php // echo $form->field($model, 'release_date') ?>

    <?php // echo $form->field($model, 'stars') ?>

    <?php // echo $form->field($model, 'video') ?>

    <?php // echo $form->field($model, 'image') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/movies/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MoviesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Movies';
//$this->params['breadcrumbs'][] = $this->title;
?>

<?php
if (Yii::$app->user->isGuest) {
    ?>
    <h1 class="text-center">Login to get access to this page!</h1>
    <?php
} else {

    foreach ($models as $movie) {

        ?>

        <div class="panel panel-default text-center">
            <div class="movie panel-heading">
                <h3>
                    <a href="<?= Url::to(['movies/view', 'id' => $movie->id]) ?>">
                        <?= $movie->title . ' (' . $movie->year . ')'; ?>
                    </a>
                </h3>
            </div>
            <div class="panel-body">
                <div class="col-md-4">
                    <?php if ($movie->image) { ?>
                        <img src="<?= '/' . $movie->image; ?>" class="col-xs-12">
                    <?php } ?>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-xs-6 text-right">
                            Genre:
                        </div>
                        <div class="col-xs-6 text-left">
                            <?= $movie->genre; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 text-right">
                            Release date:
                        </div>
                        <div class="col-xs-6 text-left">
                            <?php
                            $release_date = date("d.m.Y", strtotime($movie->release_date));
                            echo $release_date;
                            ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 text-right">
                            Duration:
                        </div>
                        <div class="col-xs-6 text-left">
                            <?= $movie->duration; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 text-right">
                            Director:
                        </div>
                        <div class="col-xs-6 text-left">
                            <?= $movie->director; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 text-right">
                            Stars:
                        </div>
                        <div class="col-xs-6 text-left">
                            <?= $movie->stars; ?>
                        </div>
                    </div>

                    <div class="clearfix feature"></div>

                    <div class="panel panel-default">
                        <div class="panel-heading">PLOT</div>
                        <div class="panel-body">
                            <?= $movie->plot ?>
                        </div>
                    </div>

                </div>
                <div class="col-md-4">
                    <iframe class="col-xs-12 no-padding" src="<?= $movie->video; ?>" frameborder="0"
                            allowfullscreen></iframe>
                </div>
            </div>
        </div>

    <?php }

    echo \yii\widgets\LinkPager::widget([
        'pagination' => $pages,
    ]);

} ?>

frontend/views/movies/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Movies */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Movies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel panel-default text-center">
    <div class="movie panel-heading">
        <h3>
            <a href="<?= Url::to(['movies/view', 'id' => $model->id]) ?>">
                <?= $model->title . ' (' . $model->year . ')'; ?>
            </a>
        </h3>
    </div>
    <div class="panel-body">
        <div class="col-md-4">
            <?php if ($model->image) { ?>
                <img src="<?= 'http://backend.dev/' . $model->image; ?>" class="col-xs-12">
            <?php } ?>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-xs-6 text-right">
                    Genre:
                </div>
                <div class="col-xs-6 text-left">
                    <?= $model->genre; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 text-right">
                    Release date:
                </div>
                <div class="col-xs-6 text-left">
                    <?php
                    $release_date = date("d.m.Y", strtotime($model->release_date));
                    echo $release_date;
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 text-right">
                    Duration:
                </div>
                <div class="col-xs-6 text-left">
                    <?= $model->duration; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 text-right">
                    Director:
                </div>
                <div class="col-xs-6 text-left">
                    <?= $model->director; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 text-right">
                    Stars:
                </div>
                <div class="col-xs-6 text-left">
                    <?= $model->stars; ?>
                </div>
            </div>

            <div class="clearfix feature"></div>

            <div class="panel panel-default">
                <div class="panel-heading">PLOT</div>
                <div class="panel-body">
                    <?= $model->plot ?>
                </div>
            </div>

        </div>
        <div class="col-md-4">
            <iframe class="col-xs-12 no-padding" src="<?= $model->video; ?>" frameborder="0"
                    allowfullscreen></iframe>
        </div>
    </div>
</div>